### ISSUE TITLE
Support panel resize

### ISSUE THREAD

**Issue by steelbrain** [steelbrain/linter-ui-default#14]
Just like in the previous UI

**Comment by corysimmons** [comment]
Will this allow the panel to be moved from bottom to sides as well by chance?

**Comment by steelbrain** [comment]
@corysimmons I would love to have an image or something to show me what you're saying

**Comment by corysimmons** [comment]
http://codepen.io/corysimmons/pen/LGyjoM?editors=110

Like, maybe have a setting to put the linter on the bottom or right side of the screen?

I ask because I never use the right side of my screen for anything whatsoever, but routinely have to mess with my code and Atom settings to keep the Linter out of the way.

I think this change would make it a bit less intrusive.

**Comment by steelbrain** [comment]
@corysimmons There's an Atom option `Show virtual space at bottom of file`, that's what you need. Error messages are usually quite long, showing them on a side end up being quite uncomfortable for users

**Comment by corysimmons** [comment]
Cool, I know this isn't an issue with the linter, but could you tell me how to set up that particular setting? Google isn't being very helpful.

**Comment by steelbrain** [comment]
@corysimmons Forgive me for I have miswritten the name of the config, the name is actually `Scroll Past End` and is available on front page of settings view

**Comment by corysimmons** [comment]
Perfect, thanks!
