### ISSUE TITLE
Make the whole linter output row clickable

### ISSUE THREAD

**Issue by aneilbaboo** [steelbrain/linter-ui-default#217]
## Issue Type
Feature request

## Issue Description

It would be nice if the entire row of the Linter output panel was clickable.  The hit target of the Line text is quite small.

<img width="903" alt="screen shot 2017-03-18 at 10 39 04 am" src="https://cloud.githubusercontent.com/assets/2592723/24074917/4ab8a8cc-0bcf-11e7-9126-c038bfb064f3.png">

**Comment by steelbrain** [comment]
Actually, you don't have to press just the text, anything in the row really :)

**Comment by aneilbaboo** [comment]
Hmm... Maybe I'm seeing a bug then?  Here's a GIF of me clicking around on the Linter error panel.

![linter-output-panel](https://cloud.githubusercontent.com/assets/2592723/24077422/006c8ef6-0c0a-11e7-8264-cfd2636c1fba.gif)

**Comment by steelbrain** [comment]
Ahh, will fix :D

**Comment by steelbrain** [comment]
Thanks for the patience everyone. Previously `Line` and `File` were clickable in the bottom panel, as of https://github.com/steelbrain/linter-ui-default/pull/248, the description will be clickable as well.

I haven't made severity and the provider columns clickable because they might confuse people in that clicking them will make Table sort by them or something. They are small columns anyway so I think it should be fine
