### ISSUE TITLE
Error tooltip visuals

### ISSUE THREAD

**Issue by henrikdahl** [steelbrain/linter-ui-default#219]
How come the error tooltip doesn't follow the same convention as the atom built in tooltip? This inconsistency seems unnecessary and just makes it looks incoherent.

Built in:
<img width="114" alt="skarmavbild 2017-03-20 kl 14 43 49" src="https://cloud.githubusercontent.com/assets/1430576/24102263/aa6c0766-0d7b-11e7-82e3-be68efec4063.png">
 
Linter error:
<img width="428" alt="skarmavbild 2017-03-20 kl 14 43 54" src="https://cloud.githubusercontent.com/assets/1430576/24102277/b56bb30a-0d7b-11e7-9dcd-500f7dcc73e4.png">

For example the fact that the built in one is rounded compare to the square linter one ✌️ 

Additionally the link icon is malpositioned.

**Comment by tuomashatakka** [comment]
I have been wondering this as well. I really do like linter's (and intentions') tooltip style but it makes the UI look cluttered. Imagine if every package implemented their own styles for tooltips :) 

Don't know what would be a good solution for this though. 

But the mispositioning of tooltips really bothers me - I can't set the tooltips follow keyboard position since the tooltip overlaps with cursor's current position making it impossible to type (there is always an error message while a word is not completed)

**Comment by steelbrain** [comment]
Fixed in master (see #301 and the tooltip icons PR)
Will be part of the next release
