### ISSUE TITLE
Default Keymaps?

### ISSUE THREAD

**Issue by spalger** [steelbrain/linter-ui-default#221]
Just upgraded to linter v2 and instantly missed the default keymap for moving to the next linter error (https://github.com/steelbrain/linter/commit/eea5d22be6d91fc226b26d7a0f0cbe4678c88df8). Would linter-ui-default be a good place to put that back?

**Comment by steelbrain** [comment]
Hi @spalger,

`linter-ui-default` now has [more commands than ever](https://github.com/steelbrain/linter-ui-default/blob/bc8d281755063a769d0ea999e95e7837eb7fe8bf/lib/commands.js#L20-L46) (we should probably document them somewhere). There are several reasons as to why the default key maps were removed. One of them is that now we have just too many commands, I can't justify making users remember ~20 key combinations of my personal taste, another one is that they were conflicting too much. There aren't enough number of keys as there are packages so people were running out of key to bind.

This way, users can bind the commands that they want to the keys of their choice with more freedom than ever. It does have an initial barrier of 5 mins of config tho instead of working out of the box but I assure you that it pays back in the long run :)

**Comment by spalger** [comment]
Totally makes sense, thanks @steelbrain
