### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onSetState' of null

### ISSUE THREAD

**Issue by CKrawczyk** [steelbrain/linter-ui-default#232]
[Enter steps to reproduce:]

1. open a `.py` and this error happens.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [linter-ui-default](https://github.com/steelbrain/linter-ui-default) package 1.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'onSetState' of null

```
At /Users/coleman/.atom/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdateQueue.js:196

TypeError: Cannot read property 'onSetState' of null
    at Object.enqueueSetState (/packages/linter-ui-default/node_modules/react-dom/lib/ReactUpdateQueue.js:196:37)
    at PanelComponent.ReactComponent.setState (/packages/linter-ui-default/node_modules/react/lib/ReactComponent.js:63:16)
    at /packages/linter-ui-default/lib/panel/component.js:28:12
    at Emitter.emit (/packages/linter-ui-default/node_modules/sb-event-kit/lib/emitter.js:84:36)
    at /packages/linter-ui-default/lib/panel/delegate.js:56:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /app.asar/src/pane-container.js:348:27
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.setActiveItem (/app.asar/src/pane.js:300:22)
    at Pane.module.exports.Pane.activateItem (/app.asar/src/pane.js:452:21)
    at TabBarView.module.exports.TabBarView.onMouseDown (/app.asar/node_modules/tabs/lib/tab-bar-view.js:678:19)
```

### Commands

```
     -0:20.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-emacs-web-view-syntax.theme-atom-light-ui)
```

### Non-Core Packages

```
atom-eco 0.2.0 
atom-espresso-soda-theme 0.10.0 
atom-monokai 0.10.9 
atom-terminal 0.8.0 
autocomplete-python 1.8.62 
busy-signal 1.3.0 
clipboard-plus 0.5.1 
color-picker 2.2.5 
emacs-web-view-syntax 0.0.0 
expose 0.14.0 
file-icons 2.1.1 
git-plus undefined 
git-time-machine 1.5.7 
grammar-token-limit 0.1.1 
intentions 1.1.2 
language-babel undefined 
language-iced-coffeescript 0.1.0 
language-latex 1.0.0 
language-lua 0.9.11 
linter 2.1.2 
linter-coffeelint 1.2.1 
linter-csslint 1.3.4 
linter-eslint 8.1.4 
linter-htmlhint 1.3.2 
linter-js-standard undefined 
linter-jsxhint 0.1.2 
linter-pycodestyle 2.0.2 
linter-python 3.1.1 
linter-stylint 2.2.7 
linter-ui-default 1.2.1 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-pigments 0.2.2 
open-in-browser 0.4.7 
pigments undefined 
python-debugger 0.2.0 
react 0.16.2 
Stylus 3.1.0 
terminal-panel 1.14.1 
tomorrow-ya 1.0.2 
```

**Comment by steelbrain** [comment]
Does this happen consistently or did it happen only once?

**Comment by CKrawczyk** [comment]
Consistently, they only way to make it stop is to deactivate `linter-ui-default`.

**Comment by steelbrain** [comment]
Can you please give a list of all community installed packages?


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Coleman Krawczyk <notifications@github.com> Date: 3/27/17  4:41 PM  (GMT+05:00) To: steelbrain/linter-ui-default <linter-ui-default@noreply.github.com> Cc: Steel Brain <i@steelbrain.me>, Comment <comment@noreply.github.com> Subject: Re: [steelbrain/linter-ui-default] Uncaught TypeError: Cannot read property 'onSetState' of null (#232) 
Consistently, they only way to make it stop is to deactivate linter-ui-default.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/steelbrain/linter-ui-default","title":"steelbrain/linter-ui-default","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/steelbrain/linter-ui-default"}},"updates":{"snippets":[{"icon":"PERSON","message":"@CKrawczyk in #232: Consistently, they only way to make it stop is to deactivate `linter-ui-default`."}],"action":{"name":"View Issue","url":"https://github.com/steelbrain/linter-ui-default/issues/232#issuecomment-289428973"}}}

**Comment by CKrawczyk** [comment]
That list is in the original post.  As a side note `emacs-web-view-syntax` is local custom color theme I made.

**Comment by CKrawczyk** [comment]
The latest update has fixed this issue
