### ISSUE TITLE
Panel not hide while switching between panes.

### ISSUE THREAD

**Issue by wKich** [steelbrain/linter-ui-default#303]
Atom 1.17.0 x64
linter-ui-default 1.4.0
Mac OS X 10.12.4

![linter-ui-default](https://cloud.githubusercontent.com/assets/6397708/26141216/25d5ec0a-3af4-11e7-8f39-dbeb5b96e961.gif)

**Comment by steelbrain** [comment]
Hi @wKich 

The new docks support was very experimental and caught me off guard

I have a LOT of fixes and new UI features in master that you can hope to get within a day, the most relevant PR to your reported bug is #302

**Comment by wKich** [comment]
Oh, I didn't see PR while recording video :)

Thank you very much.

**Comment by steelbrain** [comment]
v1.5.0 is out with the fixes

**Comment by surdu** [comment]
This is still an issue for me: the panel remains open even if the panel is empty.

**Atom:** v1.18.0-beta0 x64 
**OS:** OS X El Capitan v0.11.6 (15G1217)
**linter-ui-default:** v1.5.0

**Comment by steelbrain** [comment]
Hi @surdu

Panel will no longer hide when switching panes because the definition of panes has changed a lot in the latest version of Atom. The linter panel itself is a "pane item" so we can no longer hide the linter panel when another pane item is selected, imagine clicking a github pane item in right container or the linter panel itself. They'll all hide the panel.

Therefore the way forward is to make linter panel behave like other docks and no longer hide automatically. Tho it'll still hide itself when there are no messages because it doesn't rely on any pane item state for that

**Comment by surdu** [comment]
I'm interested in hiding the linter panel when there is no message to display, which doesn't happen now.

I find myself on tabs with the search result, settings or a file that has no linting issue, yet the linter panel is shown empty.

**Comment by steelbrain** [comment]
@surdu 

Please upgrade to v1.5.1

**Comment by surdu** [comment]
Upgraded to 1.5.4, and now once is auto-hidden because it was empty, it will never re-show.

How to reproduce:
File1.js has lints
File2.js is clean

Save file1, the panel is shown. Switch tab to file 2, the panel is hidden. Switch back to file 1, no more panel :(
