### ISSUE TITLE
Panel info for closed files

### ISSUE THREAD

**Issue by skyewell** [steelbrain/linter-ui-default#540]
On version 1.7.1, with linter 2.3.0 and linter-tslint 1.10.16, Atom v1.35.1

It appears that with the option "Entire Project" selected for both "Panel Represents" and "Statusbar Represents", closed files and corresponding errors/warnings are not represented.

If I have a file open with visible errors, but then close that file.  The panel errors, status indicator, and tree view decorations all disappear.

I am not quite sure of expected behavior based on closing of https://github.com/steelbrain/linter/pull/1525, but would be happy for clarification. 

![linter](https://user-images.githubusercontent.com/48219647/55852921-b6269980-5b13-11e9-9400-bbfba3327b85.gif)

**Comment by Arcanemagus** [comment]
When a file is closed in Atom monitoring of it by Atom is stopped... meaning _most_ providers wouldn't be updating it if an external process changes the file anyway. Due to this (and to not waste memory on them) when a file is closed in Atom all messages attached to it are automatically removed.

If a provider later returns results for a closed (or never opened!) file, they are kept around and displayed for project scoped views.

So the behavior you are seeing is what is currently expected at least.

**Comment by skyewell** [comment]
ok thank you for the explanation @Arcanemagus, it's a shame these messages can't stay cached or in view but that makes sense.  Closing issue.
