### ISSUE TITLE
Slows down the editor if too many errors

### ISSUE THREAD

**Issue by aminya** [steelbrain/linter-ui-default#580]
When there are too many errors in an editor, the linter slows down the editor. The scrolling gets sluggish, and entering text gets very slow.

This happens when you open a file that has to have `lf` line-ending on a Windows machine. 

Reproduce steps on Windows:
1) git clone https://github.com/iyonaga/minimap-lens.git
2) open the project in atom with eslint plugin
3) open lib/minimap-lens.js and try to scroll or edit something. Because of line ending differences, the editor gets very slow.

**Comment by aminya** [comment]
I found out the root of this problem. It might be related to linter rather linter-UI.
 
We need to skip rendering the new messages if are the same as those that are already cached. 

I wrote this function which filters the messages based on the given propertyNames.
```js
// This fast function returns the new messages by comparing them against the cache.
// This prevents re-rendering the already rendered messages
export function newMessages(input: Array<Message>, cache: Array<Message>, propertyNames: Array<string>) {
  if (
    input === undefined ||
    cache === undefined ||
    input.length === undefined ||
    cache.length === undefined ||
    input.length !== cache.length
  ) {
    return null
  }
  const areSame = Array(input.length).fill(true)
  for (let i = 0, len = input.length; i < len; i++) {
    for (const propertyName of propertyNames) {
      if (input[i][propertyName] !== cache[i][propertyName]) {
        areSame[i] = false
      }
    }
  }
  return input.filter((m, i) => areSame[i])
}
```


For example, in `LinterUI.render` function, the following will remove the repeated messages.
```
    if (this.messages) {
      difference.added = newMessages(difference.added, this.messages, ['description', 'excerpt', 'severity', 'linterName'])
      if (difference.added  == null) {
        return
      }
    }
```

@steelbrain Is this already implemented in Linter? or it just does not work properly?

**Comment by aminya** [comment]
We should transfer this issue to linter repository. Could you do that? @steelbrain

**Comment by steelbrain** [comment]
@aminya Linter and Linter UI APIs already work based on diffs, if no lint messages change, nothing is re-rendered. As for the slow behavior when there are a lot of errors, I've been thinking, I don't think it's a good idea to have a 100k errors in a linter provider. The Atom editor cannot handle too many decorations and any change to the buffer would be slow as it'll have to recalculate all the decorations and their markers. And this goes beyond just linter, if you have that many messages, you're better off tweaking your lint config to adapt to what you have and slowly make your way to sanity. CLIs are better suited for these tasks than GUIs. So not supporting that many messages is intentional.

I'm thinking of enforcing a hard-limit on how many messages a lint-provider can provide, it'll be set at 5k (negotiable), so it doesn't break any existing sane-implementations and doesn't make the users suffer if the provider doesn't cap it themselves.

**Comment by aminya** [comment]
My problem is that the linter passes repeated  `messages` and `added` every time I save an editor. Even though they are already rendered. You can observe this by:
```
  render(difference: MessagesPatch) {
	console.log(difference.added)
	console.log(difference.messages)
```

P.S:
- the hard-limit can be useful in rare cases.
- about line-ending specifically, I think it should be fixed in linter-eslint. Unless there is a way for Linter to detect line-ending errors.
