### ISSUE TITLE
Enabling package linter and intentions that are needed for "linter-ui-default"

### ISSUE THREAD

**Issue by lua-rocks** [steelbrain/linter-ui-default#655]
How to unsubscribe from this spam on each Atom startup?

![screenshot-001](https://user-images.githubusercontent.com/82697845/123852517-125c7a80-d925-11eb-8100-8f04b8dde32a.png)

**Comment by aminya** [comment]
Disable Linter and Linter-Ui-Default package

**Comment by lua-rocks** [comment]
Of course! Better yet - "delete Atom" or "kill yourself". I was expecting a different answer, but this one will do, too. Thank you.

**Comment by steelbrain** [comment]
Woah there :)

Apologies for the confusion here @lua-rocks. `linter-ui-default` needs `linter` to function, from that notification it appears that you have disabled the `linter` package while keeping the `linter-ui-default` package enabled.

Since one needs the other to function, I would recommend you disable `linter-ui-default` as well, since it doesn't have anything to show a UI for unless `linter` is turned. No drastic actions needed :)

**Comment by lua-rocks** [comment]
Thanks for the clarification @steelbrain, but I have both packages enabled, I did not disabled `linter` and everything works fine for me except this annoying message.

**Comment by steelbrain** [comment]
I see, then the only missing piece in the puzzle would be the `intentions` package. Do you have it installed / activated?

**Comment by lua-rocks** [comment]
Yes, you're right, I don't have it. Thank you very much just installed it and my problem is solved! But to tell you the truth I uninstalled it before because I don't really understand what it does. I use Atom only for the lua language and the `intensions` package seems to be useless for my needs.

**Comment by aminya** [comment]
Do you disable the intentions package every time you load Atom?

**Comment by lua-rocks** [comment]
@aminya I just didn't know that it is required and removed it a long time ago.

**Comment by lua-rocks** [comment]
Actually, I still don't know what I need it for, other than to hide this message.
